### ISSUE TITLE
Web Interface for configuring the platform

### ISSUE THREAD

**Issue by Amberdr0p** [semiotproject/semiot-platform#107]
We need a UI for configuring the platform and device drivers.

TODOs:
- [x] Mockup of the page(s)
- [x] System Settings
- [x] Installed drivers (#109)
- [x] Available drivers
- [x] Upload driver (via .jar or a link) (#108)

**Comment by KMax** [comment]
![semiot platform _ configuration](https://cloud.githubusercontent.com/assets/189642/11695432/2927b194-9ec0-11e5-9726-e08205c0d45e.png)

Original: https://drive.google.com/file/d/0B2UM_eIFPPHpdUZzRjFBSV9SaG8/view?usp=sharing
