### ISSUE TITLE
Create heat map for SemIoT demo version

### ISSUE THREAD

**Issue by garayzuev** [semiotproject/semiot-platform#118]
This implimentation should paint the map by extracting a group information meter from WAMP.

**Comment by soylent-grin** [comment]
What are the WAMP topics?

**Comment by garayzuev** [comment]
Now, we use `ru.semiot.alerts`

**Comment by soylent-grin** [comment]
- [x] For demo purposes, there would be only one C-SPARQL query - available at http://demo-1.semiot.ru:8085/api/query/1
- [x] This query contains .ttl with last observations; each observation contains group (doesn't matter at all), avg and diff. Based on last two we define intensity of heat spot.
- [x]  On start, we also query Fuseki for sensors' locations to point up each spot.
- [ ] We subscribe to WAMP on `ru.semiot.alerts`, and each N minutes we have new snapshot in ttl format, which has exactly the same structure, as last observations in C-SPARQL query - so we just update the whole map.
- [ ] Draw color legend
- [ ] Display timeline with ability to navigate to pervious snapshots and play them forward
  ![download 1](https://cloud.githubusercontent.com/assets/4552250/11699994/3d399798-9ed8-11e5-9837-ee4f70a8c8f9.png)

**Comment by KMax** [comment]
I suggest to move this issue to the demo's repository. And create a separate issue for each TODO item.

**Comment by soylent-grin** [comment]
:+1:
