### ISSUE TITLE
The real-time chart is not updated on new observations

### ISSUE THREAD

**Issue by KMax** [semiotproject/semiot-platform#120]
Steps to reproduce:
- load a driver, e.g. for heat meters
- open charts of a system
- open the js console
- new observations are shown in the js console, but the charts aren't updated

**Comment by soylent-grin** [comment]
Fixed.
But  I also noticed, that query to TSDB always return message like `No such name for 'metrics': '4186402112'`. This is the query for 3-month archive, constructed by the client:

```
http://demo.semiot.ru:4242/api/query?start=2015/10/13-11:37:56&end=2015/12/13-12:37:56&m=sum:4186402112{property=http_//qudt.org/vocab/quantity-ElectromotiveForce}
```

Is this query wrong?
Observations for this sensor are published on the WAMP.
