### ISSUE TITLE
Optional removal of all data from the platform when a driver is uninstalled

### ISSUE THREAD

**Issue by Amberdr0p** [semiotproject/semiot-platform#125]
- [x] build a minimal bundle which can provide a REST API
- [x] implement the removal of the data from Fuseki
- [ ] the same as above, but from OpenTSDB (#29)
- [x] implement required changes in the UI  (#123)

**Comment by KMax** [comment]
@Amberdr0p has found that we may need to upgrade OpenTSDB up to 2.2.0 version to support removal of the data from it.
