### ISSUE TITLE
Remove Online/Offline status from the Explorer

### ISSUE THREAD

**Issue by KMax** [semiotproject/semiot-platform#131]
We decided to replace in one of the next versions the online/offline status by the time of the last update and error message if it's. But the first step is to remove the status from the Explorer.

**Comment by garayzuev** [comment]
```
SELECT DISTINCT ?label ?uri ?state
WHERE {
   ?uri a ssn:System ;
       saref:hasState ?state ;
       rdfs:label ?label .
}
```

The above request expects the status of the device.
