### ISSUE TITLE
Create and initialize mysql image for storing credentials

### ISSUE THREAD

**Issue by garayzuev** [semiotproject/semiot-platform#135]

**Comment by soylent-grin** [comment]
Do we really need separate MySQL image for this? Maybe single image with web app handling LDI + authentication + explorer's frontend static server? Or `credentials` was meant for something else than authentication?

**Comment by KMax** [comment]
As I understand the reason of running MySQL in a separate container is that api-gateway's image is built on top of Centos' image which does not allow running multiple processes in the same container. Also I guess it's a best practise, right?
