### ISSUE TITLE
Add map to driver configuration page

### ISSUE THREAD

**Issue by garayzuev** [semiotproject/semiot-platform#139]
If there exists a field with type `semiot:Rectangle`, then instead of the text inputs implement a dialog for selecting a rectangle on the map.

P.S. This issue covers only the rectangle shape, but in near future will want to support a circle too.

**Comment by KMax** [comment]
@garayzuev or @Amberdr0p can you check the name of the type, is it `semiot:Rectangle` or the name is different?

**Comment by Amberdr0p** [comment]
`semiot:GeoRectangle`
