### ISSUE TITLE
Access control to the WAMP broker

### ISSUE THREAD

**Issue by KMax** [semiotproject/semiot-platform#144]
- Integrated with the Platform's security mechanism
- Any authorized client has access to all topics

**Comment by KMax** [comment]
@garayzuev, @soylent-grin We need to find a way to give access to the Explorer to the router. Currently, the Explorer can't connect without credentials to it.

**Comment by soylent-grin** [comment]
Authorization from browser to WAMP seems to work correctly; but new observations and systems are in JSON-LD format, so real-time data would not work as expected before #166 would be closed
