### ISSUE TITLE
Implement driver for Mercury 270

### ISSUE THREAD

**Issue by KMax** [semiotproject/semiot-platform#148]
Device:
- expose a CoAP API to access the device measurements,
- notify the subscribers about new measurements, no more frequently than each 5 sec.

Driver:
- subscribe to the measurements

**Comment by KMax** [comment]
@garayzuev we need your help here.

**Comment by garayzuev** [comment]
Closed by commit [a0bfbc6](https://github.com/semiotproject/semiot-drivers/commit/a0bfbc62c148b0a3d2ea28914341a8e0792c8ab7)

**Comment by garayzuev** [comment]
Closed by commit [a0bfbc6](https://github.com/semiotproject/semiot-drivers/commit/a0bfbc62c148b0a3d2ea28914341a8e0792c8ab7)
