### ISSUE TITLE
Web UI redesign notes

### ISSUE THREAD

**Issue by soylent-grin** [semiotproject/semiot-platform#153]
- On first run disable driver install or upload buttons before system settings are configured
- Add sidebar on configuration with menu to system settings and driver configuration
- Disable system settings change after first user
- Custom 403 page and disable config buttons when user is `user`
- Remove "" from list views
- Add favicon
- Add description to infobox on configuration page
- Add huge title on explorer's system detail
- Add page to view installed driver configuration
- Redesign system detail page:
  - Add last observation value

**Comment by garayzuev** [comment]
Password field must be hidden in login page

**Comment by soylent-grin** [comment]
@kmax @Amberdr0p in driver configuration schema, in what field are descriptions of each field located? I only see `rdfs:label` there.

**Comment by KMax** [comment]
`rdfs:label` is the field name. I suggest to use `rdfs:comment` for the description. So if a triple with this predicate found, the info sign should be shown near the field name. @soylent-grin can you move that in a separate issue?

**Comment by soylent-grin** [comment]
:+1:

**Comment by soylent-grin** [comment]
Closing issue in favor of splitted tasks #160 #159 #158 #157 #156 #155
