### ISSUE TITLE
Manage settings availability during platform workflow

### ISSUE THREAD

**Issue by soylent-grin** [semiotproject/semiot-platform#156]
- On first run disable driver install or upload buttons before system settings are configured
- Disable system settings change after first user

**Comment by soylent-grin** [comment]
It seems that we do not need to store real platform hostname (e. g. `demo.semiot.ru`) inside of the platform - `localhost` is enough for inside interaction, and for API we can rewrite `localhost` to real hostname on Nginx or Resteasy levels. 
Pros:
- More stateless platform workflow - we are not required to know if platform is configured yet or it is not (much easier to implement)
- Cleaner UI (completely remove `settings` page)
- In some cases it is better (and even the only way to do it correctly) to define hostname in API responses in runtime - for example within middle proxies with different hostnames

Cons:
- It may be harder to clusterize platform components on different hosts; but I think for that cases we must use common message bus for interaction, not HTTP calls (for example, to Felix WebConsole).

@KMax, @Amberdr0p WDYT?

**Comment by KMax** [comment]
The answer is short, we need to know the platform's hostname to generate correct URIs for devices, and etc. Therefore the hostname should be passed to device-proxy-service once and shouldn't be changed later.

**Comment by soylent-grin** [comment]
Do we need correct URIs for devices "and etc" only for correct API responses? Can the rest of the platform use URIs with `localhost`?

**Comment by KMax** [comment]
I don't really understand how we can't use different URIs of devices in different situations...

BTW: For each container `localhost` has it's own IP address.

data-archiving-service also need to know the domain name, because it generates URIs from scratch when it transforms data from Cassandra's structure back to RDF description.

**Comment by KMax** [comment]
Even if it'd work, I don't want to change this behaviour, since we don't have time for it.

**Comment by soylent-grin** [comment]
> since we don't have time for it

Ok.

**Comment by KMax** [comment]
Do `GET /config/system`, if it returns the 404 then it means that the platform wasn't configured yet. But if it returns 202, then it's already configured. 

_Currently the response body should not be used to generate the UI._
