### ISSUE TITLE
Apply RBAC to web interface

### ISSUE THREAD

**Issue by soylent-grin** [semiotproject/semiot-platform#157]
- Disable config buttons when user is user
- Custom 403 page

**Comment by soylent-grin** [comment]
This issue require `/user` service to return not only username and password, but user role too.

**Comment by KMax** [comment]
> This issue require /user service to return not only username and password, but user role too.

Done. The response on /user request will contain `role` field. Also I fixed the logout functionality. Now GET `/user/logout` should be used to logout.

**Comment by soylent-grin** [comment]
- If user has role `user`, `/index` page redirects to Explorer (unfortunately it is not as fast as desired), on Explorer page `Configuration` menu element is hidden
- 403 page is still simple but more consistent with other pages
