### ISSUE TITLE
Minor UX enchancements

### ISSUE THREAD

**Issue by soylent-grin** [semiotproject/semiot-platform#159]
- [ ] ~~Add sidebar on configuration with menu to system settings and driver configuration~~
- [x] Remove "" from list views
- [x] Add favicon
- [x] Add huge title on explorer's system detail

**Comment by KMax** [comment]
@soylent-grin Can you update this issue? Mark what was done so far and if the whole issue isn't finish yet, move it out of the scope of the milestone. Thanks!

**Comment by KMax** [comment]
Since we plan to get rid of the system settings page, I suggest to skip the first subtask about adding a sidebar.
