### ISSUE TITLE
Reimplement system detail page in explorer to a dashboard

### ISSUE THREAD

**Issue by soylent-grin** [semiotproject/semiot-platform#160]
- Add last observation value 
- Reduce charts' size

Here is an example of dashboard we want to implement: http://www.responsivemiracle.com/wp-content/uploads/triangular-html5-responsive-theme-desktop-full.jpg

**Comment by soylent-grin** [comment]
Observations:
- Huge last observation value, small timestamp and id

Processes:
- Separate block for process
- For each available action - button in block
- Params for action - in dialog
- Highlight button that refers to the last actuation

**Comment by KMax** [comment]
Everything works as expected. Closing
