### ISSUE TITLE
Adapt Explorer to new observations' JSON-LD API

### ISSUE THREAD

**Issue by soylent-grin** [semiotproject/semiot-platform#164]
Everyting changed.. again.
Request schema: http://{host}:8787/observations?system_id={systemId}&sensor_id={sensorId}&start=2016-03-07T13:27:15

**Comment by KMax** [comment]
The Explorer shouldn't use any API except the api-gateway's one.

**Comment by soylent-grin** [comment]
Api Gateway request schema: http://{host}/systems/2918069529/observations?sensor_id=113496665-humidity&start=2016-03-07T15:27:15

**Comment by soylent-grin** [comment]
Looks like there is an issue with observations' querying on API gateway side

**Comment by Amberdr0p** [comment]
Filter for sensors has been added to query of the system observations. 

@soylent-grin the request to http://{host}/systems/{system_id}/observations?sensor_id={sensor_id}&start=2016-03-07T15:27:15 should work now. It should return observations only for the given sensor.

**Comment by soylent-grin** [comment]
@KMax @Amberdr0p, can you please provide here actual format of new observations, coming from WAMP?

**Comment by KMax** [comment]
Look at https://github.com/semiotproject/semiot-platform/issues/170

**Comment by soylent-grin** [comment]
#173 is about messages of new registered systems, I asked about messages of new observations.
