### ISSUE TITLE
Set up HTTPS for the platform

### ISSUE THREAD

**Issue by KMax** [semiotproject/semiot-platform#172]
Access to the platform should be available only via HTTPS, because we may transfer private information between the client and the platform.

Probably, we just need to configure NGINX for that.

**Comment by KMax** [comment]
https://www.odoo.com/forum/help-1/question/nginx-reverse-proxy-on-80-443-32052

**Comment by KMax** [comment]
Current version on [enable_https](https://github.com/semiotproject/semiot-platform/tree/enable_https) branch.

Some URLs are not HTTPS-ready, e.g.:
- GET http://localhost/config/DriversInstalled

Blocked URLs (message "Blocked loading mixed active content"):
- http://fonts.googleapis.com/css?family=Roboto:300,400,500,700
- http://fezvrasta.github.io/bootstrap-material-design/dist/js/material.min.js
- http://cdn.leafletjs.com/leaflet-0.7/leaflet.css
- http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js

As a result:
- TypeError: $.material is undefined
- ReferenceError: L is not defined
- Can't save driver configuration

**Comment by KMax** [comment]
Fixed all blocked URLs except: http://korona.geog.uni-heidelberg.de/tiles/roadsg/x={x}&y={y}&z={z}. The HTTPS is not supported I guess.

@soylent-grin Do you have an idea how to fix it?

**Comment by soylent-grin** [comment]
We can use Mapnik tile server, which supports HTTPS: https://tiles.wmflabs.org/bw-mapnik/11/1195/596.png

**Comment by KMax** [comment]
> Some URLs are not HTTPS-ready, e.g.:

Looks like the API Gateway should be configured to redirect to HTTPS URLs or use relative URLs only (it's a better option). In example: the `j_security_check` servlet redirects to `http://`.

**Comment by KMax** [comment]
According to @soylent-grin we will have to also move to Secure WebSocket to work within HTTPS.
