### ISSUE TITLE
Add CORS HTTP headers to API responses

### ISSUE THREAD

**Issue by soylent-grin** [semiotproject/semiot-platform#174]
For now, `/systems/` is not available from another host. This is critical for local development and future third-party API consumers.

**Comment by soylent-grin** [comment]
For some reason, just patching `proxy.conf` in frontend image did not help.

**Comment by KMax** [comment]
I forgot to mention this issue in the https://github.com/semiotproject/semiot-platform/commit/5f80d02edccfe4533a3a7600b2930f44a7269940 commit. Do we have anything else to fix or it can be closed?

**Comment by soylent-grin** [comment]
It can be closed.
