### ISSUE TITLE
Auth doesn't work for all URLs

### ISSUE THREAD

**Issue by KMax** [semiotproject/semiot-platform#178]
At least for /systems/ the authentication doesn't work, I guess there are some other ones too.

**Comment by soylent-grin** [comment]
@KMax @garayzuev any ideas, how to develop UI locally (on localhost) now? API is not available due to this issue.
Perhaps I can fake cookies, but that's bad

**Comment by soylent-grin** [comment]
If we are going to declare API as public (and suppose that is would be consumed from third-party host), we should provide documentation about how to get credentials (e.g. `cookie`) and how to inject them to each request.

**Comment by soylent-grin** [comment]
Anyway, I think we must implement auth through pure HTTP request (as addition to auth through webform) (without redirect, only with returning cookie) - this might be enough for the first time both for developers and API consumers.

**Comment by KMax** [comment]
> Perhaps I can fake cookies, but that's bad

We already discussed that some time ago and you didn't have any concern :) It was suggested to auth via browser and then to use a rest client in the same browser.

> Anyway, I think we must implement auth through pure HTTP request

As understand you mean the BASIC auth, right? I'm okay with that, but only if you will be able to support an alternative auth method, e.g. FORM-based or OAuth-based.
