### ISSUE TITLE
Prevent HTML5 History API drawbacks

### ISSUE THREAD

**Issue by soylent-grin** [semiotproject/semiot-platform#180]
Using of modern HTML5 routing in explorer (which avoid `#` in URL path) and content negotiation has one flaw: being on explorer page, we can not navigate to, for example, driver config page - clicking on link does not perform as expected and triggers explorer's route change to `/config/AvailableDrivers`; but there is now Angular route for this URL, so we see empty explorer page. When we refresh page - we are on expected driver configuration page.
This is why bad practice to host both SPA with HTML5 routing and regular HTML pages on the same base URL. Will try to find appropriate way to do this.

**Comment by KMax** [comment]
@soylent-grin Is there a quick fix which we could apply for 1.0.6?
