### ISSUE TITLE
JSP code instead username

### ISSUE THREAD

**Issue by garayzuev** [semiotproject/semiot-platform#188]
If you append new user and sign in with new user's credentials, you can see JSP code instead username (`<%=request.getRemoteUser()%>`)

**Comment by KMax** [comment]
As discussed with @soylent-grin the UI should request the username from the REST API, instead of using JSP functionality.

**Comment by KMax** [comment]
@soylent-grin I don't see this issue any more, is it fixed?

**Comment by soylent-grin** [comment]
I did not modify code for this issue; perhaps, workaround on web.xml during other issue fixes was enough.
As I understood, problem was in `index.html` with JSP code, that processed as HTML, not JSP. Id you don't see this issue - close
