### ISSUE TITLE
Web-UI should listen for registered device to turn off

### ISSUE THREAD

**Issue by garayzuev** [semiotproject/semiot-platform#20]

**Comment by soylent-grin** [comment]
See #21

**Comment by KMax** [comment]
@garayzuev @soylent-grin  Is it a duplicate of #21 issue?

**Comment by soylent-grin** [comment]
No, this task is for webUI, #21 - for DeviceProxy.
BTW, webUI already have [listener](https://github.com/semiotproject/semiot-platform/blob/master/web-ui/src/js/models/system-list.js#L29) for this action - on WAMP topic `ru.semiot.devices.turnoff`
