### ISSUE TITLE
Request for observations of lamp fails

### ISSUE THREAD

**Issue by soylent-grin** [semiotproject/semiot-platform#204]
`https://demo.semiot.ru/systems/1231231231231230/observations` redirects to 
`https://demo.semiot.ru/systems/1231231231231230/observations?start=%3Chtml%3E%0A%3Chead%3E%0A%3Cmeta+http-equiv%3D%22Content-Type%22+content%3D%22text%2Fhtml%3Bcharset%3DISO-8859-1%22%2F%3E%0A%3Ctitle%3EError+500+%3C%2Ftitle%3E%0A%3C%2Fhead%3E%0A%3Cbody%3E%0A%3Ch2%3EHTTP+ERROR%3A+500%3C%2Fh2%3E%0A%3Cp%3EProblem+accessing+%2Fobservations%2Flatest%2Ftime.+Reason%3A%0A%3Cpre%3E++++Request+failed.%3C%2Fpre%3E%3C%2Fp%3E%0A%3Chr+%2F%3E%3Ci%3E%3Csmall%3EPowered+by+Jetty%3A%2F%2F%3C%2Fsmall%3E%3C%2Fi%3E%0A%3C%2Fbody%3E%0A%3C%2Fhtml%3E%0A`

**Comment by KMax** [comment]
The lamp doesn't have observations, so this link should be ignored
