### ISSUE TITLE
Device Proxy service should notify to WAMP that particular device has turned off

### ISSUE THREAD

**Issue by garayzuev** [semiotproject/semiot-platform#21]

**Comment by soylent-grin** [comment]
Also, ontology should be extended to make available distinction between online and offline sensors

**Comment by soylent-grin** [comment]
Now device state is hardcoded ("online"), and web-UI listens WAMP topic `ru.semiot.devices.turnoff` to change it. Next message expected:

```
{
   "device": "${SENSOR_TOPIC}",
   "state": "offline/online"
}
```

**Comment by Amberdr0p** [comment]
```
@prefix saref: <http://ontology.tno.nl/saref#>. 
<ws://wamprouter/ws?topic=10.0.0.11.60003.meter.temperature.obs> saref:hasState saref:OffState.
```

or

```
@prefix saref: <http://ontology.tno.nl/saref#>. 
<ws://wamprouter/ws?topic=10.0.0.11.60003.meter.temperature.obs> saref:hasState saref:OnState.
```

**Comment by Amberdr0p** [comment]
`@prefix saref: <http://ontology.tno.nl/saref#>. 
<coap://10.0.0.11:40006/meter> saref:hasState saref:OffState.`

**Comment by garayzuev** [comment]
It has been tested. After a while after switching off (about 2 minutes) states change.
