### ISSUE TITLE
Pagging for the list of systems

### ISSUE THREAD

**Issue by KMax** [semiotproject/semiot-platform#214]
Currently the API returns the whole list of systems (GET to `/systems`). The list may be too big to handle it.
- [x] API Gateway should be updated to implement the pagging in the API
- [x] Explorer should be updated to support the pagging

**Comment by KMax** [comment]
The API is quite simple. The `page` and `size` query params were introduced where the last one is optional, by default the page size is 20.
- GET request to /systems will redirect to /systems?page=0&size=20
- GET request to /systems?page=1&size=10 will return the second 10 items
- GET request to /systems?page=0 will return the first 20 items

The list of items is accessible through the `hydra:member` property as it was before.

**Comment by KMax** [comment]
The total items in the collection is accessible through `hydra-filter:viewOf` -> `hydra:totalItems`.

**Comment by KMax** [comment]
The URL in the browser should be equal to the URL which was used to get the page. E.g.:
- GET to `/systems` redirects to `/systems?page=1&size=10`, so the URL in the browser should be `/systems?page=1&size=10`, but not `/systems`
- GET to `/systems?page=2` redirects to `/systems?page2&size=10`, so the URL in the browser should be `/systems?page2&size=10`, but not `/systems?page=2`

**Comment by soylent-grin** [comment]
Client-side redirects (with History API) considered harmful; they break `back` browser button.
Why can't we assume that `/systems` leads to API request `/systems`, that istself redirect (on HTTP - not browser - level) to `/systems?page=1&size=10`?

**Comment by KMax** [comment]
Why is it considered harmful? Because it creates a new entry in the history? And if we "press" back we will back to /systems and we will have a cycle, right? If so can we instead of creating a new entry, replace it?

What about the second example? Is it possible to implement?

**Comment by soylent-grin** [comment]
> If so can we instead of creating a new entry, replace it

ok..

> What about the second example?

second is the same as first. 

I will implement it.
