### ISSUE TITLE
Data Analyzing Service RESTful JSON API

### ISSUE THREAD

**Issue by garayzuev** [semiotproject/semiot-platform#28]
Wildfly is running into Docker and available on 8085 port.

Provided:
1. **GET** on `${HOSTNAME}:8085/analysing-service-1.0.0-SNAPSHOT/rest/`  -  start service, if not error returned 200 Ok and message "WAMP connection started";
2. **GET** on `${HOSTNAME}:8085/analysing-service-1.0.0-SNAPSHOT/rest/qs`  -  if queries not empty returned 200 Ok and queries as WILDCARD_TYPE, else returned 404 Not Found;
3. **DELETE** on `${HOSTNAME}:8085/analysing-service-1.0.0-SNAPSHOT/rest/qs`  -  removed all queries and returned 200 Ok;
4. **POST** on `${HOSTNAME}:8085/analysing-service-1.0.0-SNAPSHOT/rest/`  as PLAIN_TEXT  -  added new querie and returned 200 Ok;
5. **GET** on `${HOSTNAME}:8085/analysing-service-1.0.0-SNAPSHOT/rest/count`  -  returned count of queries;
6. **GET** on `${HOSTNAME}:8085/analysing-service-1.0.0-SNAPSHOT/rest/${id}`  -  returned querie (if exist, else returned 404 Not Found) and returned 200 Ok;
7. **DELETE** on `${HOSTNAME}:8085/analysing-service-1.0.0-SNAPSHOT/rest/${id}`  -  returned removing querie and 200 Ok (if exist, else returned 404 Not Found);

**Comment by KMax** [comment]
I know we talked about that, but I just want to write it down here:
1. Get rid of this, instead of that we should relay on the EJB lifecycle.
2.  If there is no any query registered, return just 404 code and nothing else. The payload should be empty.

Can we get rid of the war's name in the URL? I suggest to place it in the root.

**Comment by soylent-grin** [comment]
First of all, get rid of `/analysing-service-1.0.0-SNAPSHOT/` in URLs.
Second - I suggest to use `/api/` common API methods prefix.
According to that:

### Query CRUD API

<table>
<tr>
    <th>Description</th>
    <th>HTTP Method</th>
    <th>Relative URL</th> 
    <th>Query text</th>
    <th>Answer text</th>
</tr>
<tr>
    <td>Get all registered queries</td>
    <td>GET</td>
    <td><pre>/api/query/</pre></td> 
    <td></td>
    <td>
         <pre lang="javascript">
[
  {
    "name": "MachineTool Query",
    "created": 105354377234, // UNIX Timestamp
    "id": 1,
    "text": "SELECT {...}",
  }
]
         </pre>
    </td>
</tr>
<tr>
    <td>Create new query</td>
    <td>POST</td>
    <td><pre>/api/query/</pre></td> 
    <td>        
         <pre lang="javascript">
{
   "name": "MachineTool Query",
   "text": "SELECT {...}"
   // timestamp must be set on the server
}
        </pre>
    </td>
    <td>
         <pre lang="javascript">
{
   "name": "MachineTool Query",
   "created": 105354377234, // UNIX Timestamp
   "id": 1,
   "text": "SELECT {...}",
}
        </pre>
    </td>
</tr><tr>
    <td>Delete query</td>
    <td>DELETE</td>
    <td><pre>/api/query/:id</pre></td> 
    <td>        
    </td>
    <td>
    </td>
</tr>
</table>

### Events CRUD API

<table>
<tr>
    <th>Description</th>
    <th>HTTP Method</th>
    <th>Relative URL</th> 
    <th>Query text</th>
    <th>Answer text</th>
</tr>
<tr>
    <td>Get all events by query</td>
    <td>GET</td>
    <td><pre>/api/query/:query_id/events/</pre></td> 
    <td></td>
    <td>
         <pre lang="javascript">
[
  {
    "registered": 105354377234, // UNIX Timestamp
    "producer": "coap://10.0.0.7/meter/", // URI of device, that invoked event
    "id": 1
    // maybe, something else
  }
]
         </pre>
    </td>
</tr>
</table>

_Note_: we do not need to implement the whole "get list - get single - create - update - delete" chain; I described only methods that will be used in web UI.

**Comment by soylent-grin** [comment]
Also, it is still very strange for me, that we must initialize service due some REST call. This is inner task anyway, you should handle it by yourself (though using `wget` call after some timeout)

**Comment by garayzuev** [comment]
:query_id and :id are the same objects? And why can not we use address without /api/, e.g. /query/:id/events/?

**Comment by soylent-grin** [comment]
`:query_id` and `:id` are the same numbers and both references to particular query identifier. Prefix like `/api/` is mandatory in some cases, that can make sense in future - for example, hosting all services and web-UI under NGINX (what means - under one ip address and port). 
Well, to be general, we should use something like `/api/${SERVICE_NAME}/` prefix for each service in platform, but now `/api/` is enough.
