### ISSUE TITLE
Add an opportunity to register new driver from web-UI

### ISSUE THREAD

**Issue by soylent-grin** [semiotproject/semiot-platform#45]
> As a user I want to be able to load a driver for new type of devices and run it with the default settings.

Now we have `Felix webconsole` and a little [readme](https://github.com/semiotproject/semiot-platform#how-to-add-a-device-driver) how to do this. Thats' obviously not enough. 
My suggestion for the first version - button-link `add` on the device list page, that follows user to another page, where are described steps (with links to felix console and, maybe, our future-written wiki page), required to include third-party device to middleware.
@KMax and @Amberdr0p, what do you think?

**Comment by KMax** [comment]
I think, it's fine to continue using the Felix Web Console in v1.0.0, because we don't need anything yet that can't be done by the console. E.g. when we want to configure the RDF descriptions of the devices, then we'll need a new UI.
