### ISSUE TITLE
Implement persistent triplestore on the client

### ISSUE THREAD

**Issue by soylent-grin** [semiotproject/semiot-platform#52]
Now we have some little-functional abstraction named `Resource` ([source code](https://github.com/semiotproject/semiot-platform/blob/master/web-ui/src/js/utils/rdf.js#L32)), that can not handle nested structures. The suggestion is to implement some Angular service, that will hold all RDF data (exept of `sparq-results-json`, of course) and expose some search API.
Service should be built on top of `N3.Store`.

**Comment by soylent-grin** [comment]
Issue comes from https://github.com/semiotproject/semiot-platform/blob/master/web-ui/src/js/controllers/system-detail.js#L173

**Comment by KMax** [comment]
I think, I had something similar in DAAFSE, take a look at https://github.com/ailabitmo/DAAFSE/blob/master/alert-service/src/main/webapp/js/ng-rdfresource/ng-rdfresource.js
