### ISSUE TITLE
After receive new testemony charts isn't correct display

### ISSUE THREAD

**Issue by garayzuev** [semiotproject/semiot-platform#55]
If you open a page of device and new testemony are received charts isn't display

**Comment by soylent-grin** [comment]
Trying to fix with [this](https://github.com/semiotproject/semiot-platform/commit/3a6fa19cff3368e79c4cf1b7001da16b6201996a) commit..

**Comment by soylent-grin** [comment]
Observations now are parsed correctly, but charts are still misleading because of impositioning themselves. Would be fixed within #60.
