### ISSUE TITLE
The search isn't work for fullname of device

### ISSUE THREAD

**Issue by garayzuev** [semiotproject/semiot-platform#59]
Now the search is work for meter count, but if i put into search lint the device name (e.g., "heat" or "meter") it doesn't work.

**Comment by soylent-grin** [comment]
This is not bug - search now is case-sensitive.

**Comment by garayzuev** [comment]
It's not a bug, but I think search should be work for fullname, because label is enhancement

**Comment by soylent-grin** [comment]
It _works_ for fullname, you just need to type `Heat` instead of `heat` :)

**Comment by garayzuev** [comment]
All right, don't you think about to abandon case-sensitive?
