### ISSUE TITLE
Show the version of SemIoT Platform in the Web Ui

### ISSUE THREAD

**Issue by KMax** [semiotproject/semiot-platform#64]
We have two type of versions:
- the version of "public" releases which we distribute via Docker Hub and according to [How-to-prepare-release](https://github.com/semiotproject/semiot-platform/wiki/How-to-prepare-release) wiki page, this version is the same as the tag in Guthub.
- the version of "internal" builds which should be derived from the commit number or the build number.

**Comment by soylent-grin** [comment]
Let's have SemVer variant - MAJOR_RELEASE.MINOR_RELEASE.PATCH, where
MAJOR_RELEASE - constant is some file, edited by developers on each release
MINOR_RELEASE - doesn't matter; 0 as default. Not changing.
PATCH - build number, set automatically on Jenkins.

As a result - after build we have some `version` file with this SemVer-version, that is queried by interface on start.

**Comment by soylent-grin** [comment]
Implemented. `Major` is set [directly](https://github.com/semiotproject/semiot-platform/blob/master/web-ui/src/js/config.js#L9), `Minor` is a build parameter in Jenkins (default now is 1), `Patch` is amount of commits.
![image](https://cloud.githubusercontent.com/assets/4552250/10842645/494aacc8-7f04-11e5-8c12-a55d9da2f7cc.png)

**Comment by KMax** [comment]
Okay, this is a possible option to use the number of commits, but doesn't follow the SemVer schema. I suggest to another approach which actually follow the schema:
- for public releases we have three numbers, e.g. 1.0.0 or 1.0.1
- for pre-releases uses an addition to the version which is date and time, e.g. 1.0.1-20151030125230

The date and time could be used from the last commit or the last build, but 1.0.1 could go from a file which is located in the repo.

**Comment by KMax** [comment]
Instead of the date and time we could use the number of the last commit included in the build.

**Comment by soylent-grin** [comment]
We use continuous integration, aren't we? Many of current commits are bug-fixes now, so changing `Patch` filed from commit to commit is not aboard from [SemVer spec](http://semver.org/). Milestones are setting according to next `Minor` (as for now) and `Major` releases, and only they are public - `Patch` filed is for developers mostly.
Your variant implies not to use `Minor` version, because we do not have pure "bug fix release" and "new features release"

**Comment by soylent-grin** [comment]
For now, each commit provide new release - changing `Patch` field is conform way to fixate this.
