### ISSUE TITLE
Timeline selects incorrect range

### ISSUE THREAD

**Issue by garayzuev** [semiotproject/semiot-platform#66]
if you are in a device page and get new testemony timeline selects incorrect range

**Comment by KMax** [comment]
I'm not sure that this issue should be fixed. It's probably a bug of Highcharts

**Comment by soylent-grin** [comment]
If "incorrect range" is exactly the same range, that was on page load - it is fine; range simply does not change, but new observation with timestamp === NOW is obviously out of that range. 
BTW, you still can see new observation on minimap on the bottom of the chart - can you?

**Comment by soylent-grin** [comment]
This is the limitation of Bootstrap datetimepicker and is not a bug.
