### ISSUE TITLE
Newly added devices don't appear in the list on the WAMP message

### ISSUE THREAD

**Issue by KMax** [semiotproject/semiot-platform#73]
Steps to reproduce:
- Deploy the platform
- Open the list view
- In another tab load the machinetool driver
- Look at the first tab, the list will be empty

**Comment by soylent-grin** [comment]
Are there messages from WAMP, that you can see on the client ( e. g. in browser console)?

**Comment by soylent-grin** [comment]
Yes they are. Problem starts with changed format of device description.

**Comment by soylent-grin** [comment]
Note that by [this](https://github.com/semiotproject/semiot-platform/commit/c7332337a78ea4e1d47a946a6f3aeb393cc51173) commit I changed `ssn:hasSybsystem` to `ssn:hasSubSystem` both in device descriptions and webUI, so platform should be redeployed.
