### ISSUE TITLE
How to gracefully stop TSDB

### ISSUE THREAD

**Issue by KMax** [semiotproject/semiot-platform#74]
Currently TSDB doesn't flush the observations which are kept in the memory to disk before stop, therefore we lose these observations. So we need to find a way to somehow request TSDB to flush the observations to the disk before the stop.

**Comment by garayzuev** [comment]
This issue is related with #68 TSDB doesn't start after reboot

**Comment by garayzuev** [comment]
If you stop hbase by command `docker stop -t 60 hbase` or another command with waiting while hbase shut down, hbase stopes gracefully and then TSDB stopes the same. And this case provides that hbase and TSDB start good.
