### ISSUE TITLE
Create Jenkins Job for Device Proxy Service drivers

### ISSUE THREAD

**Issue by soylent-grin** [semiotproject/semiot-platform#77]
In order to make drivers' JARs easy to access (and to upload to Felix WebConsole) we should have some job (jobs) that simple build drivers with Maven and publish result with [Copy Artifact Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Copy+Artifact+Plugin)

**Comment by KMax** [comment]
What about the [semiot-device-prototype](https://github.com/semiotproject/semiot-platform/tree/master/device-proxy-service-drivers/semiot-device-prototype) driver? Does it work?

**Comment by Amberdr0p** [comment]
It was designed for Alexey`s devices. It was not tested, probably it will be removed.
