### ISSUE TITLE
Non-public version number should be accompanied with the date and time of the last commit

### ISSUE THREAD

**Issue by KMax** [semiotproject/semiot-platform#84]
- The current version number should be read from the .version file from, regardless of the type of the release
- If the build is not a public release, then the date and time of the last commit should be extracted at the build time of web ui by the following command:

```
git show -s --format=%ci | tr -d \- | tr -d : | tr -d [:blank:] | cut -b 1-14
```

The build job of web ui should be updated to be triggered per each commit in the repository regardless of the particular changes.

As the result:
- public version number should look like `1.0.1`
- non-public - `1.0.1-SNAPSHOT-20151031153522`

P.S. This issue is a part of discussion initiated in #64.

**Comment by soylent-grin** [comment]
If flag `Release` on Jenkins is not set - `-SNAPSHOT-$TIMESTAMP` is appending to version

**Comment by KMax** [comment]
No, only `-$TIMESTAMP`, because `-SNAPSHOT` is set in the `.version` file.

**Comment by soylent-grin** [comment]
Why? If so - developer must manually set \ remove `-SNAPSHOT` to the `.version` on private \ public release - we don't want to have `-SNAPSHOT` in public version, aren't we?

**Comment by KMax** [comment]
Oookaay :) Makes sense, let's add `-SNAPSHOT` at the build time

**Comment by KMax** [comment]
Looks like the version number is not read from `.version`, because I always see `1.0.1`.

**Comment by soylent-grin** [comment]
In repository I see 1.0.1 - https://github.com/semiotproject/semiot-platform/blob/master/web-ui/.version

**Comment by KMax** [comment]
Okay, next time I'll use an absolute path :) Because I meant .version in the root directory. Can you update the build to use this [.version](https://github.com/semiotproject/semiot-platform/blob/master/.version)?

**Comment by soylent-grin** [comment]
Done. `web-ui/.version` removed from the repo.
