### ISSUE TITLE
Web UI is hardcoded to work with demo.semiot.ru domain

### ISSUE THREAD

**Issue by KMax** [semiotproject/semiot-platform#86]
According to 4 line in the [config.js](https://github.com/semiotproject/semiot-platform/blob/master/web-ui/src/js/config.js#L4) file, web ui will send some request to `demo.semiot.ru` domain even if it's deploy on another server. To reproduce, deploy the platform locally.

**Comment by soylent-grin** [comment]
No it won't - as it commented, target host would be demo.semiot.ru only on local development, otherwise - it would be web UI host, from where page loaded.

**Comment by soylent-grin** [comment]
I guess the reason of misunderstood: I used to develop UI without local deploy of the whole platform and suggestion was that I would always work with remote backend. Seems like if you want to develop both frontend and backend locally - you should edit [config.js](https://github.com/semiotproject/semiot-platform/blob/master/web-ui/src/js/config.js#L4) file manually.

**Comment by KMax** [comment]
Can we make it configurable? By default we shouldn't use `demo.semiot.ru`, even on the local machine, because it won't be expected by the user. I understand that it's convenient for the development, then change `config.js` and that's it.

**Comment by soylent-grin** [comment]
I hardly thought about how to make it _more configurable_ than it is, but I invented nothing.
`demo.semiot.ru` is removed from code, and developer should manually add it back if it is needed.

**Comment by KMax** [comment]
Deployed the platform on my local machine. When opened the system page, the Explorer tried to request the system with URI containing `demo.semiot.ru` domain.
