### ISSUE TITLE
Label of a device received from WAMP is used incorrectly

### ISSUE THREAD

**Issue by KMax** [semiotproject/semiot-platform#87]
When the description of the device queried from Fuseki then we'll see `Heat Meter #60000` (which is expected), by if it was received from WAMP then we'll see `"Heat Meter #60000"`. In case of the machine tools the label received from WAMP will be `"Machine Tool #222...."@en`.

**Comment by soylent-grin** [comment]
Tested on mock systems. Should be approved on real systems.
