### ISSUE TITLE
Prepare a host to run the latest release of the platform

### ISSUE THREAD

**Issue by KMax** [semiotproject/semiot-platform#92]
We're using `demo.semiot.ru` as a development server, it means that from time to time it's broken which is bad sometimes. E.g. we can use `winghouse.semiot.ru` to host a stable deployment of the latest version and host the simulators on another VM which doesn't have a public IP.

Thoughts?

**Comment by soylent-grin** [comment]
Do we really need stable deploy? Aren't we have it already on [МКС](http://81.211.100.222/) server?
