### ISSUE TITLE
Change the naming schema used for writing observations in TSDB

### ISSUE THREAD

**Issue by KMax** [semiotproject/semiot-platform#96]
The goal is to write all system's observations in a single metric, instead of having a separate metric per observing property. This simplifies the finding the metric used for a system and moreover we already store the URI of the property in `property` tag.

**Comment by KMax** [comment]
We need to update the web-ui to support the new behaviour.

**Comment by soylent-grin** [comment]
Please, provide new TSDB URL to query archive data for particular sensor of particular system.

**Comment by Amberdr0p** [comment]
1) Values for all sensors in system
http://demo.semiot.ru:4242/api/query?start=2015/11/20-19:28:06&end=2015/11/24-20:28:06&m=sum:3288124911{property=*}
2) Values for one sensor
http://demo.semiot.ru:4242/api/query?start=2015/11/20-19:28:06&end=2015/11/24-20:28:06&m=sum:3288124911{property=http_//qudt.org/vocab/quantity-ThermodynamicTemperature}
